package org.folio.rdf4ld.mapper;

import static org.assertj.core.api.Assertions.assertThat;
import static org.eclipse.rdf4j.model.util.Values.iri;
import static org.folio.ld.dictionary.PredicateDictionary.ADMIN_METADATA;
import static org.folio.rdf4ld.test.TestUtil.toJsonLdString;

import java.io.IOException;
import java.util.UUID;
import org.eclipse.rdf4j.model.vocabulary.RDF;
import org.eclipse.rdf4j.rio.RDFFormat;
import org.eclipse.rdf4j.rio.Rio;
import org.folio.ld.dictionary.model.ResourceEdge;
import org.folio.rdf4ld.test.MonographUtil;
import org.folio.rdf4ld.test.SpringTestConfig;
import org.folio.spring.testing.type.IntegrationTest;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.boot.test.context.SpringBootTest;

@IntegrationTest
@EnableConfigurationProperties
@SpringBootTest(classes = SpringTestConfig.class)
class InstanceAdminMetadataMappingIT {

  private static final String BF_LOCAL_TYPE = "http://id.loc.gov/ontologies/bibframe/Local";

  @Autowired
  private Rdf4LdMapper rdf4LdMapper;

  @Test
  void mapBibframe2RdfToLd_shouldReturnMappedInstanceWithoutAdminMetadata() throws IOException {
    // given
    var input = this.getClass().getResourceAsStream("/rdf/instance_admin_metadata.json");
    var model = Rio.parse(input, "", RDFFormat.JSONLD);

    // when
    var result = rdf4LdMapper.mapBibframe2RdfToLd(model);

    // then
    assertThat(result).isNotEmpty().hasSize(1);
    var instance = result.iterator().next();
    assertThat(instance.getDoc()).isNotNull();
    assertThat(instance.getOutgoingEdges().stream().anyMatch(edge ->
      edge.getPredicate().equals(ADMIN_METADATA)
    )).isFalse();
  }

  @Test
  void mapLdToBibframe2Rdf_shouldReturnMappedRdfInstanceWithAdminMetadata() throws IOException {
    // given
    var instance = MonographUtil.createInstance(null, null);
    var folioUuid = UUID.randomUUID().toString();
    var adminMetadata = MonographUtil.createAdminMetadata("in00123", folioUuid);
    instance.addOutgoingEdge(new ResourceEdge(instance, adminMetadata, ADMIN_METADATA));
    var expected = new String(this.getClass().getResourceAsStream("/rdf/instance_admin_metadata.json").readAllBytes())
      .replaceAll("INSTANCE_ID", instance.getId().toString())
      .replaceAll("ADMIN_METADATA_ID", adminMetadata.getId().toString())
      .replaceAll("FOLIO_UUID", folioUuid);

    // when
    var model = rdf4LdMapper.mapLdToBibframe2Rdf(instance);
    // bnode IDs generated by profile application are not available ahead of time
    var locals = model.getStatements(null, RDF.TYPE, iri(BF_LOCAL_TYPE));
    for (var local : locals) {
      var subject = local.getSubject().stringValue();
      if (subject.contains("CONTROL_NUMBER_1")) {
        expected = expected.replaceAll("CONTROL_NUMBER_1_ID", subject);
      } else if (subject.contains("FOLIO_INVENTORY_ID_1")) {
        expected = expected.replaceAll("FOLIO_INVENTORY_ID_1_ID", subject);
      }
    }

    // then
    var jsonLdString = toJsonLdString(model);
    assertThat(jsonLdString).isEqualTo(expected);
  }
}
